#!/bin/bash
# sysinfo_page - A script to provide system infromaation in html

#### Variables

title="System information for $HOSTNAME"
RIGHT_NOW=$(date +"%r %x %Z")
TIME_STAMP="Last updated on $RIGHT_NOW"

#### Functions

system_info()
{
    # Temporary function stub
    echo "function system_info"
}

show_uptime()
{

    # Temporary function stub
    echo "function show_uptime"
}

drive_space()
{
    
    # Temporary function stub
    echo "function drive_space"
}

home_space()
{

    # Temporary function stub
    echo "function home_space"
}

#### Main

cat <<- _EOF_
	<html>
	<head>
	  <title>
	  $title $HOSTNAME
	  </title>
	</head>
	<body>
	  $title 
	  <p>$TIME_STAMP</p>
      $(system_info)
      $(show_uptime)
      $(drive_space)
      $(home_space)
    </body>
    </html>
_EOF_

