#!/bin/bash
# sysinfo_page - A script to provide system infromaation in html

#### Variables

title="System information for $HOSTNAME"
RIGHT_NOW=$(date +"%r %x %Z")
TIME_STAMP="Last updated on $RIGHT_NOW"

#### Functions

system_info()
{
    echo "<h2>System release info</h2>"
    echo "<p>Function not yet implemented</p>"
}

show_uptime()
{

    echo "<h2>System uptime</h2>"
    echo "<pre>"
    uptime
    echo "</pre>"
}

drive_space()
{
    
    echo "<h2>Filesystem space</h2>"
    echo "<pre>"
    df -h
    echo "</pre>"
}

home_space()
{
    # Only superuser shoult execute this
    if [ $(id -u) = "0" ]; then
        echo "<h2>Home directory pace used by user</h2>"
        echo "<pre>"
        du -s /home/* | sort -nr
        echo "</pre>"
    fi
}

#### Main

cat <<- _EOF_
	<html>
	<head>
	  <title>
	  $title $HOSTNAME
	  </title>
	</head>
	<body>
	  $title 
	  <p>$TIME_STAMP</p>
      $(system_info)
      $(show_uptime)
      $(drive_space)
      $(home_space)
    </body>
    </html>
_EOF_
