#!/bin/bash

title="System information for $HOSTNAME"
RIGHT_NOW=$(date +"%r %x %Z")
TIME_STAMP="Last updated on $RIGHT_NOW"
cat <<- _EOF_
	<html>
	<head>
	  <title>
	  $title $HOSTNAME
	  </title>
	</head>
	<body>
	</body>
	  $title 
	  <p>$TIME_STAMP</p>
    </html>
_EOF_

